
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio            # Name of this ArgoCD application
  namespace: argocd
spec:
  project: portfolio                 # ArgoCD Project
  source:
    repoURL: https://github.com/JanitChawla/Lineten.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:                     # Enable auto-sync
      prune: true
      selfHeal: true
